package main

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"database/sql"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
)

const databasePoolSize = 5

type user struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	Role      string `json:"role"`
	Status    int    `json:"status"`
	CreatedAt string `json:"created_at"`
}

type store struct{ db *sql.DB }

func openStore(databaseURL string) (*store, error) {
	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(databasePoolSize)
	db.SetMaxIdleConns(databasePoolSize)
	db.SetConnMaxIdleTime(5 * time.Minute)
	db.SetConnMaxLifetime(30 * time.Minute)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf("连接 PostgreSQL: %w", err)
	}
	statements := []string{
		`CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(32) NOT NULL UNIQUE,
            username_normalized VARCHAR(32) NOT NULL UNIQUE,
            password_salt VARCHAR(64) NOT NULL,
            password_hash VARCHAR(64) NOT NULL,
            role VARCHAR(16) NOT NULL CHECK(role IN ('admin','user')),
            status SMALLINT NOT NULL DEFAULT 1 CHECK(status IN (1,2)),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )`,
		`CREATE TABLE IF NOT EXISTS sessions (
            token_hash VARCHAR(64) PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            expires_at TIMESTAMPTZ NOT NULL
        )`,
		`CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions(expires_at)`,
		`CREATE TABLE IF NOT EXISTS uploads (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id),
            channel_name VARCHAR(120) NOT NULL,
            channel_type INTEGER NOT NULL,
            success BOOLEAN NOT NULL,
            message VARCHAR(500) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )`,
		`CREATE INDEX IF NOT EXISTS uploads_created_at_idx ON uploads(created_at DESC)`,
		`CREATE TABLE IF NOT EXISTS app_settings (
            id SMALLINT PRIMARY KEY CHECK(id=1),
            newapi_base_url TEXT NOT NULL,
            newapi_access_token_encrypted TEXT NOT NULL,
            newapi_user_id VARCHAR(32) NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )`,
	}
	for _, statement := range statements {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			db.Close()
			return nil, fmt.Errorf("初始化数据库: %w", err)
		}
	}
	return &store{db: db}, nil
}

func (s *store) close() error { return s.db.Close() }

type storedPlatformSettings struct {
	BaseURL              string
	AccessTokenEncrypted string
	UserID               string
}

func (s *store) getPlatformSettings() (storedPlatformSettings, error) {
	var settings storedPlatformSettings
	err := s.db.QueryRow(`SELECT newapi_base_url,newapi_access_token_encrypted,newapi_user_id FROM app_settings WHERE id=1`).Scan(&settings.BaseURL, &settings.AccessTokenEncrypted, &settings.UserID)
	return settings, err
}

func (s *store) savePlatformSettings(settings storedPlatformSettings) error {
	_, err := s.db.Exec(`INSERT INTO app_settings(id,newapi_base_url,newapi_access_token_encrypted,newapi_user_id,updated_at)
        VALUES(1,$1,$2,$3,NOW())
        ON CONFLICT(id) DO UPDATE SET newapi_base_url=EXCLUDED.newapi_base_url,newapi_access_token_encrypted=EXCLUDED.newapi_access_token_encrypted,newapi_user_id=EXCLUDED.newapi_user_id,updated_at=NOW()`, settings.BaseURL, settings.AccessTokenEncrypted, settings.UserID)
	return err
}

func (s *store) ensureAdmin(username, password string) (string, error) {
	var count int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM users`).Scan(&count); err != nil || count > 0 {
		return "", err
	}
	if password == "" {
		password = randomToken(18)
	}
	if err := validateCredentials(username, password); err != nil {
		return "", err
	}
	salt := randomToken(18)
	_, err := s.db.Exec(`INSERT INTO users(username,username_normalized,password_salt,password_hash,role,status) VALUES($1,$2,$3,$4,'admin',1)`, strings.TrimSpace(username), strings.ToLower(strings.TrimSpace(username)), salt, derivePassword(password, salt))
	return password, err
}

func validateCredentials(username, password string) error {
	username = strings.TrimSpace(username)
	if len(username) < 3 || len(username) > 32 {
		return errors.New("用户名长度必须为 3~32")
	}
	if len(password) < 8 || len(password) > 128 {
		return errors.New("密码长度必须为 8~128")
	}
	return nil
}

func derivePassword(password, salt string) string {
	value := []byte(salt + "\x00" + password)
	for i := 0; i < 120_000; i++ {
		sum := sha256.Sum256(value)
		value = sum[:]
	}
	return base64.RawURLEncoding.EncodeToString(value)
}

func scanUser(row interface{ Scan(...any) error }) (user, error) {
	var u user
	var createdAt time.Time
	err := row.Scan(&u.ID, &u.Username, &u.Role, &u.Status, &createdAt)
	u.CreatedAt = createdAt.UTC().Format(time.RFC3339)
	return u, err
}

func (s *store) authenticate(username, password string) (user, error) {
	var salt, expected string
	var u user
	var createdAt time.Time
	err := s.db.QueryRow(`SELECT id,username,role,status,created_at,password_salt,password_hash FROM users WHERE username_normalized=$1`, strings.ToLower(strings.TrimSpace(username))).Scan(&u.ID, &u.Username, &u.Role, &u.Status, &createdAt, &salt, &expected)
	if err != nil || u.Status != 1 || subtle.ConstantTimeCompare([]byte(derivePassword(password, salt)), []byte(expected)) != 1 {
		return user{}, errors.New("用户名或密码错误")
	}
	u.CreatedAt = createdAt.UTC().Format(time.RFC3339)
	return u, nil
}

func (s *store) createSession(userID int64, ttl time.Duration) (string, error) {
	token := randomToken(32)
	_, err := s.db.Exec(`INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,$3)`, sha256String(token), userID, time.Now().Add(ttl))
	return token, err
}

func (s *store) sessionUser(token string) (user, error) {
	return scanUser(s.db.QueryRow(`SELECT u.id,u.username,u.role,u.status,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>NOW() AND u.status=1`, sha256String(token)))
}

func (s *store) deleteSession(token string) {
	_, _ = s.db.Exec(`DELETE FROM sessions WHERE token_hash=$1`, sha256String(token))
}

func (s *store) listUsers() ([]user, error) {
	rows, err := s.db.Query(`SELECT id,username,role,status,created_at FROM users ORDER BY id`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	users := make([]user, 0)
	for rows.Next() {
		u, err := scanUser(rows)
		if err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	return users, rows.Err()
}

func (s *store) createUser(username, password string) (user, error) {
	if err := validateCredentials(username, password); err != nil {
		return user{}, err
	}
	username = strings.TrimSpace(username)
	salt := randomToken(18)
	u, err := scanUser(s.db.QueryRow(`INSERT INTO users(username,username_normalized,password_salt,password_hash,role,status) VALUES($1,$2,$3,$4,'user',1) RETURNING id,username,role,status,created_at`, username, strings.ToLower(username), salt, derivePassword(password, salt)))
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "unique") {
			return user{}, errors.New("用户名已存在")
		}
		return user{}, err
	}
	return u, nil
}

func (s *store) updateUser(id int64, status *int, password string) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var role string
	if err := tx.QueryRow(`SELECT role FROM users WHERE id=$1 FOR UPDATE`, id).Scan(&role); err != nil {
		return errors.New("用户不存在")
	}
	if role == "admin" && status != nil && *status != 1 {
		return errors.New("不能禁用管理员账号")
	}
	if status != nil {
		if *status != 1 && *status != 2 {
			return errors.New("无效用户状态")
		}
		if _, err := tx.Exec(`UPDATE users SET status=$1 WHERE id=$2`, *status, id); err != nil {
			return err
		}
	}
	if password != "" {
		if len(password) < 8 || len(password) > 128 {
			return errors.New("密码长度必须为 8~128")
		}
		salt := randomToken(18)
		if _, err := tx.Exec(`UPDATE users SET password_salt=$1,password_hash=$2 WHERE id=$3`, salt, derivePassword(password, salt), id); err != nil {
			return err
		}
	}
	if (status != nil && *status == 2) || password != "" {
		if _, err := tx.Exec(`DELETE FROM sessions WHERE user_id=$1`, id); err != nil {
			return err
		}
	}
	return tx.Commit()
}

func (s *store) addUpload(ctx context.Context, userID int64, name string, channelType int, success bool, message string) {
	if len(message) > 500 {
		message = message[:500]
	}
	_, _ = s.db.ExecContext(ctx, `INSERT INTO uploads(user_id,channel_name,channel_type,success,message) VALUES($1,$2,$3,$4,$5)`, userID, name, channelType, success, message)
}

func (s *store) listUploads() ([]map[string]any, error) {
	rows, err := s.db.Query(`SELECT l.id,u.username,l.channel_name,l.channel_type,l.success,l.message,l.created_at FROM uploads l JOIN users u ON u.id=l.user_id ORDER BY l.id DESC LIMIT 200`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]map[string]any, 0)
	for rows.Next() {
		var id int64
		var username, name, message string
		var channelType int
		var success bool
		var createdAt time.Time
		if err := rows.Scan(&id, &username, &name, &channelType, &success, &message, &createdAt); err != nil {
			return nil, err
		}
		items = append(items, map[string]any{"id": id, "username": username, "channel_name": name, "channel_type": channelType, "success": success, "message": message, "created_at": createdAt.UTC().Format(time.RFC3339)})
	}
	return items, rows.Err()
}

func randomToken(size int) string {
	buf := make([]byte, size)
	if _, err := rand.Read(buf); err != nil {
		panic(err)
	}
	return base64.RawURLEncoding.EncodeToString(buf)
}

func sha256String(value string) string {
	sum := sha256.Sum256([]byte(value))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}
